### ISSUE TITLE
[9.1] What's left to finalize the updater .... 

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/updater#303]
_I will add individual issues for each topic where the discussion should take place_
- [x] find a solution for occ command execution within webui #261 
- [ ] clear separation of updater responsibilities vs core responsibilities #304 
- [ ] updater deployment and version definition #295 
- [ ] updater self-update

**Comment by PVince81** [comment]
@VicDeo what's the status ?

**Comment by DeepDiver1975** [comment]
lets move this on to 9.2

**Comment by PVince81** [comment]
@DeepDiver1975 @VicDeo backlog or do we want this for 10.0 ?

**Comment by PVince81** [comment]
I think the updater is already in good shape right now and I don't think we want to invest more time in it currently. Moving to backlog
